FROM maven:3.8.1-openjdk-17-slim AS build
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package

FROM openjdk:17-slim
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/target/thesis-1.0-SNAPSHOT.jar /usr/src/app
ENTRYPOINT ["java", "-jar", "thesis-1.0-SNAPSHOT.jar"]