version: '2' # to use the older docker compose version installed on the storage server
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - ./jars:/usr/src/app/jars
      - ./config.properties:/usr/src/app/config.properties
      - ./logs:/usr/src/app/logs
    environment:
      - DIRECTORY=jars
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  mariadb_data: