version: '2' # to use the older docker compose version installed on the storage server
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - ${JARS_DIRECTORY}:/usr/src/app/jars
      - ./config.properties:/usr/src/app/config.properties
      - ./logs:/usr/src/app/logs
    environment:
      - DIRECTORY=jars
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "3306:3306"
    volumes:
      - ./my-custom.cnf:/etc/mysql/mariadb.conf.d/my-custom.cnf
      - ${MARIADB_DATA_LOCATION}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db