version: '2' # to use the older docker compose version installed on the storage server
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - /home/dan/tudelft/master_thesis/jar-vulnerability-detection/big_jars:/usr/src/app/jars
      - ./config.properties:/usr/src/app/config.properties
      - ./logs:/usr/src/app/logs
    environment:
      - DIRECTORY=jars
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    shm_size: '1gb'
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}

volumes:
  postgresql_data:
